apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
  namespace: java
  labels:
    app: hello-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java
  template: # <-- This should be inside "spec"
    metadata:
      labels:
        app: hello-java
    spec:
      containers: # <-- This should be inside "template.spec"
        - name: hello-java
          image: sharathi25/hello-java:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
